// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_C-GdrUmT6OEfFApsuGtXdU8YMm0Vi9Q',
    appId: '1:427104807114:web:d3d36ae68adc4f1c756c33',
    messagingSenderId: '427104807114',
    projectId: 'cartella-979b4',
    authDomain: 'cartella-979b4.firebaseapp.com',
    storageBucket: 'cartella-979b4.appspot.com',
    measurementId: 'G-SE3WQ8VL73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ahZodzyiZ7Cgm4sF4UD5PbXUuRmdPVY',
    appId: '1:427104807114:android:bd178cce5153506f756c33',
    messagingSenderId: '427104807114',
    projectId: 'cartella-979b4',
    storageBucket: 'cartella-979b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-zLfs0ZAugC9kqzYbwgh3c0afQed7M8',
    appId: '1:427104807114:ios:76632358e383ae40756c33',
    messagingSenderId: '427104807114',
    projectId: 'cartella-979b4',
    storageBucket: 'cartella-979b4.appspot.com',
    iosBundleId: 'com.example.cartella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX-zLfs0ZAugC9kqzYbwgh3c0afQed7M8',
    appId: '1:427104807114:ios:76632358e383ae40756c33',
    messagingSenderId: '427104807114',
    projectId: 'cartella-979b4',
    storageBucket: 'cartella-979b4.appspot.com',
    iosBundleId: 'com.example.cartella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_C-GdrUmT6OEfFApsuGtXdU8YMm0Vi9Q',
    appId: '1:427104807114:web:1090d41256ea78ac756c33',
    messagingSenderId: '427104807114',
    projectId: 'cartella-979b4',
    authDomain: 'cartella-979b4.firebaseapp.com',
    storageBucket: 'cartella-979b4.appspot.com',
    measurementId: 'G-H0BY3C5Y63',
  );

}